### ISSUE TITLE
Message attachments does not open correctly

### ISSUE THREAD

**Issue by pheinila** [espoon-voltti/evaka#2412] opened 2022-05-02 05:06 UTC
If a message contains an attachment with type docx, eVaka provides a file with no file name extension or type data (see attached picture). This causes that on windows machines you have to rename the file before it can be opened. And with iPhones it can not be opened at all. Tried with Safari and Chrome.

![image](https://user-images.githubusercontent.com/9930089/166186555-f92deb20-e03c-413f-8cc3-2d08fddc13bd.png)

**Comment by Wnt** [comment] 2023-09-15 11:28
Looks like this issue is no longer reproducible in current version of eVaka. It must have been fixed in previous changes to Content-Disposition header handling or attachment handling in general.

Thanks for reporting this and apologies for the delayed response!

**Closed by Wnt** 2023-09-15 11:28 UTC
